#!/bin/sh

set -o errexit
set -o nounset

BREW_TAPS="adamv/alt homebrew/dupes homebrew/versions josegonzalez/php"
HOSTNAME=$(hostname)
OS=$(uname -s)

# Get the full path to the current directory.
cwd=$(pwd)
cd $(dirname $0)
root=$(pwd)
cd ${cwd}

# Symlink a bash completion file
bash_completion() {
  completion_file=$1
  completion_dir=/etc/bash_completion.d
  if which brew > /dev/null 2>&1; then
    completion_dir="$(brew --prefix)${completion_dir}"
  fi
  symlink ${completion_file} ${completion_dir}/$(basename ${completion_file})
}

bytemark_box() {
  [ ${HOSTNAME} = "mcdermottr.vm.bytemark.co.uk" ]
}

# Print the command we're going to run and (if DRY_RUN is not set) run it.
cmd() {
  echo $*
  if [ ${DRY_RUN:-unset} = "unset" ]; then
    $*
  fi
}

# Ensure a package is installed
pkg() {
  for package_name in $*; do
    case ${OS} in
      (Darwin)
        # Make sure homebrew is installed
        if ! which brew > /dev/null 2>&1; then
          cmd ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
          for tap in ${BREW_TAPS}; do
            if [ "$(brew tap | grep ${tap})" != "${tap}" ]; then
              cmd brew tap ${tap}
            fi
          done
        fi

        # Adjust the installer, package name and/or compile flags if necessary.
        installer="brew"
        flags=""
        case ${package_name} in
          (boto|httpie|paramiko|pyflakes|requests|requests-oauth|tornado)
            installer="pip"
            ;;
          (php)
            package_name=php54
            flags="--with-mysql --with-pgsql --with-fpm --with-intl"
            ;;
          (vagrant)
            installer="gem"
            ;;
          (xdebug|xhprof)
            package_name="php54-${package_name}"
            ;;
        esac

        # Trigger the install
        case ${installer} in
          (brew)
            if ! brew list ${package_name} > /dev/null; then
              cmd brew install ${package_name} ${flags}
            fi
            ;;
          (gem)
            # Make sure the Homebrew ruby is installed first.
            if ! brew list ruby > /dev/null; then
              cmd brew install ruby
            fi

            # Now install the gem if necessary
            if [ "$(gem list ${package_name} | grep ${package_name})" = "" ]; then
              cmd gem install ${package_name}
            fi
            ;;
          (pip)
            if ! which pip > /dev/null 2>&1; then
              if [ ${DRY_RUN:-set} != "set" ]; then
                curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python
              else
                echo "[Install pip]"
              fi
            fi

            package_dir=/Library/Python/2.7/site-packages/${package_name}
            if [ ${package_name} = "requests-oauth" ]; then
              package_dir=/Library/Python/2.7/site-packages/oauth_hook
            fi
            if [ ! -d ${package_dir} ]; then
              cmd sudo pip install ${package_name}
            fi
            ;;
          (*)
            # This should be unreachable.
            echo "Invalid installer: ${installer}"
            exit 1
            ;;
        esac
        ;;
      (Linux)
        if [ -f /etc/debian_version ]; then
          case ${package_name} in
            (ctags)
              package_name="exuberant-ctags"
              ;;
          esac
          if ! dpkg -s ${package_name} > /dev/null 2>&1; then
            cmd sudo aptitude install ${package_name}
          fi
        else
          echo "Unsupported Linux variant."
          exit 1
        fi
        ;;
    esac
  done
}

# Add a PEAR channel
pear_channel() {
  for channel in $*; do
    if ! pear channel-info ${channel} > /dev/null 2>&1; then
      cmd sudo pear channel-discover ${channel}
    fi
  done
}

# Install a PEAR package
pear_install() {
  package_name=$1
  if [ $# -gt 1 ]; then
    package_source=$2
  else
    package_source=$1
  fi
  if which pear > /dev/null 2>&1; then
    if [ "X$(pear list -a | grep ^${package_name}\ )X" = "XX" ]; then
      cmd sudo pear install --alldeps ${package_source}
    fi
  else
    pkg php
  fi
}

# Symlink a file from this repo.
symlink() {
  file=$1
  if [ $# -gt 1 ]; then
    target=$2
    if [ "$(echo ${target} | grep ^/)" != "${target}" ]; then
      target=${HOME}/${target}
    fi
  else
    target=${HOME}/${file}
  fi
  if [ "$(echo ${file} | grep ^/)" != "${file}" ]; then
    file="${root}/${file}"
  fi
  if [ ! -L ${target} ] || [ $(readlink ${target}) != ${file} ]; then
    cmd ln -fns ${file} ${target}
  fi
}

#
# Now work through all the things we need.
#

# If X11 isn't installed, we need to prompt for XQuartz before going further.
if [ ${OS} = "Darwin" ]; then
  if [ ! -d /opt/X11 ]; then
    echo "Install XQuartz before going any further."
    echo "http://xquartz.macosforge.org/"
    exit 1
  fi
fi

# Install the packages we need
pkg bash bash-completion ctags curl gnupg git nmap vim wget
if [ ${OS} = "Darwin" ]; then
  pkg boto go hub httpie imagemagick mercurial mysql nginx paramiko php \
    postgresql pstree pyflakes redis requests requests-oauth ruby tornado \
    vagrant xdebug xhprof
fi
if bytemark_box; then
  pkg mutt
fi
if ! which make > /dev/null 2>&1; then
  pkg make
fi

# Generate .gitconfig
if [ ${DRY_RUN:-set} != "set" ]; then
  sed -e s/___EMAIL___/$(git config user.email || echo conor@mcdermottroe.com)/ ${root}/.gitconfig.template > ${HOME}/.gitconfig
fi

# Now link in the dotfiles
symlink .bash_login
symlink .bashrc
symlink .cvsignore
symlink .inputrc
if bytemark_box; then symlink .muttrc; fi
symlink .tcsh
symlink .tcshrc
symlink .vim
symlink .vimrc

# Extra bash completions
bash_completion modules/completion-ruby/completion-bundle
bash_completion modules/completion-ruby/completion-gem
bash_completion modules/completion-ruby/completion-jruby
bash_completion modules/completion-ruby/completion-rails
bash_completion modules/completion-ruby/completion-rake
bash_completion modules/completion-ruby/completion-ruby
bash_completion modules/vagrant-bash-completion/vagrant
if [ ${OS} = "Darwin" ]; then
  bash_completion $(brew --prefix)/Library/Contributions/brew_bash_completion.sh
fi

# Prune the bash completions to the things we have
completion_dir=/etc/bash_completion.d
if which brew > /dev/null 2>&1; then
  completion_dir="$(brew --prefix)${completion_dir}"
fi
for _completion_file in $(find ${completion_dir} -type l -o -type f); do
  _have=$(awk '/^have / { print $2; exit}' ${_completion_file})
  if [ -n "${_have}" ]; then
    if ! type ${_have} > /dev/null 2>&1; then
      cmd rm ${_completion_file}
    fi
  fi
done

# PHP extras
if [ ${OS} = "Darwin" ]; then
  pear_channel pear.pdepend.org pear.phpmd.org pear.phpunit.de \
    components.ez.no pear.symfony-project.com pear.phpundercontrol.org \
    pear.symfony.com
  pear_install PHP_Depend pdepend/PHP_Depend-beta
  pear_install PHP_PMD phpmd/PHP_PMD-alpha
  pear_install phpcpd phpunit/phpcpd
  pear_install PhpDocumentor PHPDocumentor
  pear_install PHP_CodeSniffer
  pear_install PHP_CodeBrowser phpunit/PHP_CodeBrowser-alpha
  pear_install PHPUnit phpunit/PHPUnit
fi

# Sort out the bin directory
[ -d ${HOME}/bin ] || cmd mkdir ${HOME}/bin
for file in $(find ${root}/bin -type f); do
  filename=$(basename ${file})
  case ${filename} in
    (ipsort|mailtail|mark_as_read)
      if bytemark_box; then
        symlink ${file} bin/$(basename ${file})
      fi
      ;;
    (*)
      symlink ${file} bin/$(basename ${file})
      ;;
  esac
done
symlink modules/git-wip/git-wip bin/git-wip
