#!/bin/sh

set -o errexit
set -o nounset

OS=$(uname -s)

# Work out of the same directory as this script.
cd $(dirname $0)

# Print the command we're going to run and (if DRY_RUN is not set) run it.
cmd() {
  echo $*
  if [ ${DRY_RUN:-unset} = "unset" ]; then
    $*
  fi
}

# Update this repo
cmd git pull
cmd git submodule foreach git pull

# Upgrade the packages
case ${OS} in
  (Darwin)
    cmd brew update
	cmd brew upgrade
    ;;
  (Linux)
    cmd sudo aptitude update
	cmd sudo aptitude safe-upgrade
    ;;
esac
